import { Inter } from "next/font/google";
import "./globals.css";
import { Red_Hat_Text } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const redHatText = Red_Hat_Text({ subsets: ["latin"] , weight: ["400", "500", "600"] , variable: "--Red_Hat_Text" });
export const metadata = {
  title: "Shopping Cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={redHatText.variable}>{children}</body>
    </html>
  );
}
